### ISSUE TITLE
Getting issue when trying to start a new chat.

### ISSUE THREAD

**Issue by supreetssethi** [microsoft/omnichannel-chat-sdk#205]
Hi All,
I have  create my omni channel setup. the initialization process is working fine.
I created a new screen for chat option in react native.
But as soon as i am trying to do chatSDK.startChat() i am getting below error 
When run on android:
`OmnichannelChatSDK/startChat/joinConversation/error Error: GetParticipants
reactConsoleErrorHandler @ ExceptionsManager.js:151
registerError @ LogBox.js:187
console.error @ LogBox.js:67
overrideMethod @ backend.js:2082
console.error @ index.js:19
(anonymous) @ OmnichannelChatSDK.js:595
step @ OmnichannelChatSDK.js:45
(anonymous) @ OmnichannelChatSDK.js:26
rejected @ OmnichannelChatSDK.js:18
tryCallOne @ core.js:37
(anonymous) @ core.js:123
(anonymous) @ JSTimers.js:248
_callTimer @ JSTimers.js:112
_callReactNativeMicrotasksPass @ JSTimers.js:162
callReactNativeMicrotasks @ JSTimers.js:413
__callReactNativeMicrotasks @ MessageQueue.js:390
(anonymous) @ MessageQueue.js:132
__guard @ MessageQueue.js:367
flushedQueue @ MessageQueue.js:131
callFunctionReturnFlushedQueue @ MessageQueue.js:116
(anonymous) @ RNDebuggerWorker.js:2`

When run on IOS.
`Error: MessagingClientConversationJoinFailure
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:534156:20)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:534215:30)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:269405:126)
    at call (native)
    at step (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:268887:23)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:268836:20)
    at rejected (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:268802:34)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25257:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25176:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25206:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25369:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2354:46)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2166:45)
    at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2338:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2165:21)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2150:33)`

Can some one help me?

**Comment by xTEddie** [comment]
> Hi All, I have create my omni channel setup. the initialization process is working fine. I created a new screen for chat option in react native. But as soon as i am trying to do chatSDK.startChat() i am getting below error When run on android: `OmnichannelChatSDK/startChat/joinConversation/error Error: GetParticipants reactConsoleErrorHandler @ ExceptionsManager.js:151 registerError @ LogBox.js:187 console.error @ LogBox.js:67 overrideMethod @ backend.js:2082 console.error @ index.js:19 (anonymous) @ OmnichannelChatSDK.js:595 step @ OmnichannelChatSDK.js:45 (anonymous) @ OmnichannelChatSDK.js:26 rejected @ OmnichannelChatSDK.js:18 tryCallOne @ core.js:37 (anonymous) @ core.js:123 (anonymous) @ JSTimers.js:248 _callTimer @ JSTimers.js:112 _callReactNativeMicrotasksPass @ JSTimers.js:162 callReactNativeMicrotasks @ JSTimers.js:413 __callReactNativeMicrotasks @ MessageQueue.js:390 (anonymous) @ MessageQueue.js:132 __guard @ MessageQueue.js:367 flushedQueue @ MessageQueue.js:131 callFunctionReturnFlushedQueue @ MessageQueue.js:116 (anonymous) @ RNDebuggerWorker.js:2`
> 
> When run on IOS. `Error: MessagingClientConversationJoinFailure at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:534156:20) at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:534215:30) at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:269405:126) at call (native) at step (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:268887:23) at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:268836:20) at rejected (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:268802:34) at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16) at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27) at apply (native) at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25257:26) at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25176:17) at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25206:17) at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:25369:44) at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2354:46) at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2166:45) at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2338:15) at flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2165:21) at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.manafeth.consumer.dev:2150:33)`
> 
> Can some one help me?

Did you try to use `v1.4.4` and above?
